name: Pygmalion Paphos Back End

permissions:
  # This is required for actions/checkout
  contents: read 

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:   

env:
  go-version: '1.19.1'
  buffalo-cli-version: '0.18.13'

jobs:
  postgres:
    name: PostgreSQL
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: paphos
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

